/*

1.总账入库表

*/
CREATE TABLE `GL_SUBJ_MONTH` (
  `STAT_DT` date NOT NULL,
  `OP_ORG_NUM` varchar(32) NOT NULL,
  `CURR_CD` varchar(8) NOT NULL,
  `GL_ACCT` varchar(32) NOT NULL,
  `GL_BAL_TYPE_CD` varchar(2) NOT NULL,
  `LAST_D_BAL` double DEFAULT 0,
  `LAST_C_BAL` double DEFAULT 0,
  `DR_AMT` double DEFAULT 0,
  `CR_AMT` double DEFAULT 0,
  `DR_BAL` double DEFAULT 0,
  `CR_BAL` double DEFAULT 0,
PRIMARY KEY(STAT_DT,OP_ORG_NUM,CURR_CD,GL_ACCT)
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

/*

2.建立科目层级

*/

CREATE TABLE `gl_acct_all` (
  `GL_ACCT3` varchar(255) DEFAULT NULL,
  `GL_ACCT_NAME3` varchar(255) DEFAULT NULL,
  `GL_ACCT2` varchar(255) DEFAULT NULL,
  `GL_ACCT_NAME2` varchar(255) DEFAULT NULL,
  `GL_ACCT1` varchar(255) DEFAULT NULL,
  `GL_ACCT_NAME1` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

;

CREATE TABLE GL_ACCT_ALL AS
SELECT
 T.GL_ACCT 					GL_ACCT3,
 T.GL_ACCT_NAME			GL_ACCT_NAME3,
 T.MAGT_GL_ACCT			GL_ACCT2,
 T2.GL_ACCT_NAME 		GL_ACCT_NAME2,
 T2.MAGT_GL_ACCT 		GL_ACCT1,
 T3.GL_ACCT_NAME 		GL_ACCT_NAME1
FROM GL_ACCT T LEFT JOIN GL_ACCT T2 ON T.MAGT_GL_ACCT = T2.GL_ACCT
               LEFT JOIN GL_ACCT T3 ON T2.MAGT_GL_ACCT = T3.GL_ACCT
WHERE 1=1
AND T.GL_ACCT_LEVEL = '3'

;

/*

IND_MAP

*/



CREATE TABLE `ind_map` (
  `TB` varchar(32) DEFAULT NULL,
  `TYPE` varchar(16) DEFAULT NULL,
  `NBR` varchar(8) DEFAULT NULL,
  `NAME` varchar(128) DEFAULT NULL,
  `GL_ACCT` varchar(32) DEFAULT NULL,
  `GL_ACCT_NAME` varchar(128) DEFAULT NULL,
  `SIGN` int(11) DEFAULT NULL,
  `IS_VALID` varchar(1) DEFAULT NULL,
  `GL_BAL_TYPE_CD` varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

;

/*

完成一级、二级科目汇总

*/
  DROP VIEW IF EXISTS V_YWZK_DETAIL;
CREATE VIEW  V_YWZK_DETAIL AS
SELECT
 T.STAT_DT,
 T.OP_ORG_NUM,
 T.CURR_CD,
 C.GL_ACCT2 AS GL_ACCT,
 '2' 		AS GL_ACCT_LEVEL,
 T.GL_BAL_TYPE_CD,
 SUM(T.LAST_D_BAL) AS LAST_D_BAL,
 SUM(T.LAST_C_BAL) AS LAST_C_BAL,
 SUM(T.DR_AMT) AS DR_AMT,
 SUM(T.CR_AMT) AS CR_AMT,
 SUM(T.DR_BAL) AS DR_BAL,
 SUM(T.CR_BAL) AS CR_BAL
FROM GL_SUBJ_MONTH T, GL_ACCT_ALL C
WHERE 1 = 1
AND T.GL_ACCT = C.GL_ACCT3
GROUP BY  T.STAT_DT ,T.OP_ORG_NUM ,T.CURR_CD ,C.GL_ACCT2,T.GL_BAL_TYPE_CD
UNION
SELECT
 T.STAT_DT,
 T.OP_ORG_NUM,
 T.CURR_CD,
 C.GL_ACCT1 AS GL_ACCT,
 '1' 		AS GL_ACCT_LEVEL,
 T.GL_BAL_TYPE_CD,
 SUM(T.LAST_D_BAL) AS LAST_D_BAL,
 SUM(T.LAST_C_BAL) AS LAST_C_BAL,
 SUM(T.DR_AMT) AS DR_AMT,
 SUM(T.CR_AMT) AS CR_AMT,
 SUM(T.DR_BAL) AS DR_BAL,
 SUM(T.CR_BAL) AS CR_BAL
FROM GL_SUBJ_MONTH T, GL_ACCT_ALL C
WHERE 1 = 1
AND T.GL_ACCT = C.GL_ACCT3
GROUP BY  T.STAT_DT ,T.OP_ORG_NUM ,T.CURR_CD ,C.GL_ACCT1,T.GL_BAL_TYPE_CD
;
/*

完成支行、分行 汇总

*/


DROP VIEW IF EXISTS V_YWZK_SUMMARY;
CREATE VIEW V_YWZK_SUMMARY AS
SELECT
	T.STAT_DT,
	T.OP_ORG_NUM,
	'4' AS ORG_LEVEL,
	T.CURR_CD,
	T.GL_ACCT,
	T.GL_ACCT_LEVEL,
	T.GL_BAL_TYPE_CD,
  T.LAST_D_BAL,
  T.LAST_C_BAL,
  T.DR_AMT,
  T.CR_AMT,
  T.DR_BAL,
  T.CR_BAL
FROM V_YWZK_DETAIL T
UNION
SELECT
	T.STAT_DT,
	G.MAGT_ORG_NUM AS OP_ORG_NUM,
	'3' AS ORG_LEVEL,
	T.CURR_CD,
	T.GL_ACCT,
	T.GL_ACCT_LEVEL,
  T.GL_BAL_TYPE_CD,
  SUM(T.LAST_D_BAL) AS LAST_D_BAL,
  SUM(T.LAST_C_BAL) AS LAST_C_BAL,
  SUM(T.DR_AMT) AS DR_AMT,
  SUM(T.CR_AMT) AS CR_AMT,
  SUM(T.DR_BAL) AS DR_BAL,
  SUM(T.CR_BAL) AS CR_BAL
FROM V_YWZK_DETAIL T, GL_ORG G
WHERE 1=1
AND T.OP_ORG_NUM = G.OP_ORG_NUM
AND G.ORG_LEVEL = '4'
GROUP BY T.STAT_DT,G.MAGT_ORG_NUM ,T.CURR_CD,T.GL_ACCT,T.GL_ACCT_LEVEL,T.GL_BAL_TYPE_CD

;

/*

ZCFZ 明细

*/


DROP VIEW  IF EXISTS V_ZCFZ_DETAIL;
CREATE VIEW V_ZCFZ_DETAIL AS
SELECT
	T.STAT_DT,
	T.OP_ORG_NUM,
	T.ORG_LEVEL,
	T.CURR_CD,
	M.TYPE,
	M.NBR,
	M.NAME,
	M.GL_ACCT,
	M.GL_ACCT_NAME,
	M.GL_BAL_TYPE_CD ,
	GEN_OFFSET_VAL(M.GL_BAL_TYPE_CD,T.LAST_D_BAL,T.LAST_C_BAL) AS LAST_BAL,
	GEN_OFFSET_VAL(M.GL_BAL_TYPE_CD,T.DR_BAL,T.CR_BAL) AS BAL
FROM V_YWZK_SUMMARY T ,IND_MAP M
WHERE 1=1
AND T.GL_ACCT = M.GL_ACCT
AND M.IS_VALID = '1'
AND M.TB = 'ZCFZ'
;

/*

LR 明细

*/
DROP VIEW  IF EXISTS V_LR_DETAIL;
CREATE VIEW V_LR_DETAIL AS
SELECT
 T.STAT_DT AS STAT_DT,
 T.OP_ORG_NUM AS OP_ORG_NUM,
 T.ORG_LEVEL AS ORG_LEVEL,
 T.CURR_CD AS CURR_CD,
 M.TYPE AS TYPE,
 M.NBR AS NBR,
 M.NAME AS NAME,
 M.GL_ACCT AS GL_ACCT,
 M.GL_ACCT_NAME AS GL_ACCT_NAME,
 M.GL_BAL_TYPE_CD AS GL_BAL_TYPE_CD, -- ,
 GEN_OFFSET_VAL(M.GL_BAL_TYPE_CD, T.DR_AMT, T.CR_AMT) AS INDIC_VAL
FROM AD_MAP2 M  , V_YWZK_SUMMARY T
WHERE 1 = 1
AND T.GL_ACCT = M.GL_ACCT
AND M.IS_VALID = '1'
AND M.TB ='LR'
;

DROP FUNCTION IF EXISTS GEN_ACCT_VAL;
CREATE FUNCTION GEN_ACCT_VAL(P_TP varchar(2),P_DV double,P_CV double)  RETURNS double
BEGIN
  DECLARE str VARCHAR(2) DEFAULT '';
  DECLARE res double DEFAULT 0 ;
  SET str = P_TP;
	IF str <> '3' THEN
		CASE str WHEN '0' THEN SET res = P_DV
			WHEN '1' THEN SET res = P_CV
			ELSE SET res = 0 END ;
		RETURN(res);
	ELSE RETURN(P_DV+P_CV);
	END IF;
END
;


DROP FUNCTION IF EXISTS GEN_ACCT_VAL;
CREATE FUNCTION GEN_ACCT_VAL(P_TP varchar(2),P_DV double,P_CV double)  RETURNS double
BEGIN
  DECLARE str1 VARCHAR(2) DEFAULT '';
  DECLARE res1 double DEFAULT 0 ;
  SET str = P_TP;

	IF str1 = '0' THEN
		SET res1 = P_DV ;
  ELSEIF str1 = '1'
		SET res1 = P_CV ;
	ELSE re1s = P_DV+P_CV ;
	END IF;
 RETURN(res1);
END
;